### ISSUE TITLE
Implementation question

### ISSUE THREAD

**Issue by flxo** [jonhoo/udp-over-tcp#2]
Hello @jonhoo 

this is just a question - not an issue :-). Feel free to burn it after reading.

I recently did something quite similar: [taper](https://github.com/flxo/taper/tree/main). It's `ethernet via tcp`. I decided rely on Tokios (util) [Framed](https://docs.rs/tokio-util/latest/tokio_util/codec/struct.Framed.html) along with [LengthDelimitedCodec](https://docs.rs/tokio-util/latest/tokio_util/codec/length_delimited/struct.LengthDelimitedCodec.html) and do the forwarding in `tokio::select!` loop. I know that is suboptimal compared a plain impl performance wise due to more copies etc.. Also the forwarding could be done in parallel with multiple threads by `dupping` the `fds`. I don't need the performance because it's just a dev tool.

I saw your code and wondered why you're doing the framing yourself? Performance? Less dependencies? Fun?

Thanks for the note about what's the issue with `socat`. Your cli looks `socat` inspired and my first thought was - why not `socat`.

cheers,

@flxo

**Comment by jonhoo** [comment]
Hey!

The main reason I didn't was because I needed to write this code rather quickly for `$REASONS`, and it was very straightforward to just write it myself. The post-hoc rationalization (which I think is still valid) is that `Framed` + `LengthDelimitedCodec` produce a `Stream<Item = Bytes>`, which means they have to allocate + copy for every received packet. `Encode` also takes a `Bytes`, which would mean allocating for every packet send. This isn't necessary when directly using the lower-level interfaces, since when reading I can simply slice into the received payload and pass that by reference to the thing that writes packets out the other end (with `Chain` allow injecting the payload header without an allocation + copy).

And yeah, I actually _tried_ to do what I needed with `socat` first, and then realized it can't actually forward UDP in a datagram-preserving way (or if it can, I have no idea how), so ended up just writing what I needed myself. And once I had done that, I figured I might as well share it 😅
